# Generated by Django 4.0.1 on 2023-03-20 16:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ABLine', 'ABLine')], max_length=255)),
                ('heading', models.DecimalField(decimal_places=15, max_digits=18)),
                ('aPoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('bPoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lastModifiedTime', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField()),
            ],
        ),
    ]
