# Generated by Django 4.0.1 on 2023-03-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
        ('techlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techline',
            name='field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fields.field'),
            preserve_default=False,
        ),
    ]
